name: Release Electron (mac / Forge)

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

permissions:
  id-token: write
  contents: read

jobs:
  build-mac:
    timeout-minutes: 120
    runs-on: macos-latest
    env:
      RELEASE_CHANNEL: dev

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22.11.0

      - name: Configure AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.ELECTRON_PUBLISH_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION || 'eu-central-1' }}

      - name: Fetch Apple credentials (Secrets Manager)
        id: apple_env
        shell: bash
        run: |
          set -euo pipefail
          OUT=$(aws secretsmanager get-secret-value --secret-id "${{ vars.APPLE_SECRET_NAME }}" --query SecretString --output text)
          jq -r '.' <<<"$OUT" > secrets.json

          APPLE_API_KEY_ID=$(jq -r '.APPLE_API_KEY_ID' secrets.json)
          APPLE_API_ISSUER_ID=$(jq -r '.APPLE_API_ISSUER_ID' secrets.json)
          P8_RAW=$(jq -r '.APPLE_API_KEY_P8 // empty' secrets.json)
          [ -z "$P8_RAW" -o "$P8_RAW" = "null" ] && { echo "APPLE_API_KEY_P8 is missing"; exit 1; }

          P8_PATH="$RUNNER_TEMP/AuthKey_${APPLE_API_KEY_ID}.p8"
          if echo "$P8_RAW" | base64 -d > "$P8_PATH" 2>/dev/null; then
            echo "decoded p8"
          else
            printf '%b' "$P8_RAW" > "$P8_PATH"
            echo "wrote p8 literal"
          fi
          chmod 600 "$P8_PATH"
          head -1 "$P8_PATH" | grep -q "BEGIN " || { echo "p8 looks wrong"; exit 1; }

          P12_B64=$(jq -r '.APPLE_DEV_ID_APP_CERT_P12 // empty' secrets.json)
          if [ -n "$P12_B64" ] && [ "$P12_B64" != "null" ]; then
            P12_PATH="$RUNNER_TEMP/dev_id_app.p12"
            printf "%s" "$P12_B64" | base64 -d > "$P12_PATH"
            PASS=$(jq -r '.APPLE_DEV_ID_APP_CERT_PASSWORD // .APPLE_CERT_P12_PASSWORD // ""' secrets.json)
            echo "::add-mask::$PASS"
            security create-keychain -p "" build.keychain
            security default-keychain -s build.keychain
            security unlock-keychain -p "" build.keychain
            security import "$P12_PATH" -k build.keychain -P "$PASS" -T /usr/bin/codesign -T /usr/bin/security
            security set-key-partition-list -S apple-tool:,apple: -s -k "" build.keychain
            echo "CSC_LINK=file://$P12_PATH"   >> $GITHUB_ENV
            echo "CSC_KEY_PASSWORD=$PASS"      >> $GITHUB_ENV
          fi

          echo "APPLE_API_KEY_ID=$APPLE_API_KEY_ID"       >> $GITHUB_ENV
          echo "APPLE_API_ISSUER_ID=$APPLE_API_ISSUER_ID" >> $GITHUB_ENV
          echo "APPLE_API_KEY_PATH=$P8_PATH"              >> $GITHUB_ENV
          echo "APPLE_TEAM_ID=${{ vars.APPLE_TEAM_ID }}"  >> $GITHUB_ENV

          PKG_VERSION=$(node -p "require('./package.json').version")
          echo "RELEASE_VERSION=$PKG_VERSION" >> $GITHUB_ENV
          echo "PUBLISH_BASE_URL=${{ vars.PUBLISH_BASE_URL }}" >> $GITHUB_ENV
          echo "PRODUCT_PATH=${{ vars.PRODUCT_PATH || 'releases' }}" >> $GITHUB_ENV

      - name: Install deps
        run: |
          npm ci


      - name: Forge make (arm64)
        env:
          MAC_NOTARIZE: "1"
          MAC_NOTARIZE_DMG: "1"
          DEBUG: "@electron-forge/*,electron-packager,electron-osx-sign"
        run: |
          npx electron-forge make --platform=darwin --arch=arm64 --targets=@electron-forge/maker-dmg

      - name: Forge make (x64)
        env:
          MAC_NOTARIZE: "1"
          MAC_NOTARIZE_DMG: "1"
          DEBUG: "@electron-forge/*,electron-packager,electron-osx-sign"
        run: |
          npx electron-forge make --platform=darwin --arch=x64 --targets=@electron-forge/maker-dmg

      - name: Show Forge output
        run: |
          echo "---- out/make ----"
          find out/make -maxdepth 3 -type f -print || true

      - name: Upload DMGs (GitHub artifact)
        if: always()
        uses: actions/upload-artifact@v4
        with:
            name: mac-dmgs
            path: out/make/**/*.dmg

      - name: Upload DMG (versioned)
        run: |
          aws s3 cp out/make/ "s3://${{ vars.S3_BUCKET }}/${{ vars.PRODUCT_PATH || 'releases' }}/${{ env.RELEASE_VERSION }}/mac/" \
            --recursive --exclude "*" --include "*.dmg" --only-show-errors

      - name: Upload DMG (latest)
        run: |
          LATEST="s3://${{ vars.S3_BUCKET }}/${{ vars.PRODUCT_PATH || 'releases' }}/latest/mac/"
          aws s3 sync out/make/ "$LATEST" --delete --exclude "*" --include "*.dmg" --only-show-errors
